services:
  xxx-changemeapp:
    image: ghcr.io/mindcollaps/xxx-changeme:next
    container_name: xxx-changemeapp
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NITRO_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test:
          - CMD-SHELL
          - 'wget --no-verbose http://127.0.0.1:3000/health || exit 1'
      interval: 30s
      timeout: 20s
      retries: 10
  db:
    image: 'postgres:18.1-alpine'
    container_name: xxx-changemedb
    volumes:
      - db_data:/var/lib/postgresql/18/docker
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
    env_file:
      - .env

volumes:
  db_data:
  redis_data:
